name: Build PermissionControl Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Build mod
      run: gradle build --stacktrace --info

    - name: Upload mod jar
      uses: actions/upload-artifact@v4
      with:
        name: PermissionControl-Mod
        path: build/libs/*.jar
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.0
        name: Release v1.0.0
        files: build/libs/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
